### ISSUE TITLE
bugfix examples/multi_agent/prison_iql.py

### ISSUE THREAD

**Issue by stevens68** [laszukdawid/ai-traineree#12]
Hi, great framework!

Seems to me that the following lines need should be changed in prison_iql.py

#8: (version 2 is deprecated)
```
from pettingzoo.butterfly import prison_v3 as prison
```

#14: to get 1 instead of (1,) 
```
obs_size = ma_task.obs_size[0]
```

**Comment by laszukdawid** [comment]
Hi @stevens68,

Thanks for letting me know :) Got caught red-handed that I haven't run all the examples after update. Will update this shortly!

I'd super appreciate letting me know anything else you find. Just finishing a different part of a big project and moving back to AI Traineree shortly.

**Comment by laszukdawid** [comment]
Closing issue. Feel free to reopen or create a new one if there's more to be done.
