### ISSUE TITLE
Dummy agent

### ISSUE THREAD

**Issue by laszukdawid** [laszukdawid/ai-traineree#16]
## What

Create an agent which returns random values according to specifications.

## Why

Mainly for testing and debugging. When running experiments there's plenty of things that'll be broken. Having agent that returns specific values we can debug where the problem is, i.e. whether that's agent, environment, life cycle management...

**Comment by LuisFMCuriel** [comment]
Not sure if this is what you meant. Please let me know if you want me to add/remove/change something.

**Comment by laszukdawid** [comment]
Merged with #24
