### ISSUE TITLE
'int' object has no attribute 'to_feature' in DQN examples

### ISSUE THREAD

**Issue by LuisFMCuriel** [laszukdawid/ai-traineree#20]
Hi,

In the documentation, https://ai-traineree.readthedocs.io/en/latest/examples.html I got the error `'int' object has no attribute 'to_feature'` when I try to run the example DQN on CartPole. I believe is because I am calling the wrong task attribute (not sure about this). Changing this `agent = DQNAgent(task.obs_size, task.action_size, n_steps=5)` to `agent = DQNAgent(task.obs_space, task.action_space, n_steps=5)` makes it work perfectly.

Regards!

**Comment by laszukdawid** [comment]
Nice catch! Yes, the documentation has been neglected for a while and is outdated. It needs an update.

**Comment by laszukdawid** [comment]
Fixed in c152b77ffa5f13f6cbd62d395d0b9127a443b30d
